#直播列表
query RecommendLivesQuery($page: Int) {
  recommendLives(page: $page) {
    paginatorInfo {
      currentPage
      hasMorePages
    }
    data {
      id
      title
      cover
      count_audience
    }
  }
}
